apiVersion: batch/v1
kind: Job
metadata:
  name: adscraper-job
spec:
  # These values will be overriden by the job runner
  parallelism: 4 # maxWorkers
  completions: 8 # Number of crawl jobs
  template:
    metadata:
      name: adscraper-job
    spec:
      containers:
        - name: crawler
          image: adscraper
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - mountPath: /home/pptruser/input
            name: input-volume
          env:
            - name: BROKER_URL
              value: amqp://guest:guest@rabbitmq-service:5672
            # Added dynamically by job runner
            # - name: QUEUE
            #   value: job1
            - name: PG_DATABASE
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: database
            - name: PG_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: user
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
            - name: PG_HOST
              value: postgres.default.svc.cluster.local
            - name: PG_PORT
              value: "5432"
      restartPolicy: OnFailure
      volumes:
        - name: input-volume
          hostPath:
            # directory location on host
            path: /input
            # this field is optional
            type: Directory
      securityContext:
        fsGroup: 999
        readOnlyRootFileSystem: false
        runAsUser: 999
        runAsGroup: 999
        allowPrivilegeEscalation: false
        capabilities:
            add:
            - SYS_ADMIN
