apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-server
  labels:
    app: job-server
spec:
  selector:
    matchLabels:
      app: job-server
  replicas: 1
  template:
    metadata:
      labels:
        app: job-server
    spec:
      containers:
        - name: job-server
          image: job-server
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: BROKER_URL
              value: amqp://guest:guest@rabbitmq-service:5672
            - name: QUEUE
              value: job1
            - name: PG_DATABASE
              valueFrom:
                secretKeyRef:
                  name: pg-conf-secret
                  key: database
            - name: PG_USER
              valueFrom:
                secretKeyRef:
                  name: pg-conf-secret
                  key: user
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-conf-secret
                  key: password
            - name: PG_HOST
              value: postgres.default.svc.cluster.local
            - name: PG_PORT
              value: "5432"

---

apiVersion: v1
kind: Service
metadata:
  name: job-server
spec:
  selector:
    app: job-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
