apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    component: rabbitmq
  name: rabbitmq-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: taskQueue
        component: rabbitmq
    spec:
      containers:
      - image: rabbitmq:3-management
        name: rabbitmq
        ports:
        - containerPort: 5672
        resources:
          limits:
            cpu: 100m
        env:
        - name: CONFIG_FILE
          value: /etc/rabbitmq-custom-conf/rabbitmq.conf
        volumeMounts:
          - name: rabbitmq-config
            mountPath: /etc/rabbitmq-custom-conf
      volumes:
        - name: rabbitmq-config
          configMap:
            name: rabbitmq-configmap
            items:
              - key: rabbitmq.conf
                path: rabbitmq.conf
