
# TODO: make dynamically customizable
apiVersion: batch/v1
kind: Job
metadata:
  name: job-wq-1
spec:
  # TODO these next two need to change based on the job
  parallelism: 2
  completions: 8
  template:
    metadata:
      name: job-wq-1
    spec:
      containers:
      - name: c
        image: adscraper
        env:
        - name: BROKER_URL
          value: amqp://guest:guest@rabbitmq-service:5672
        - name: QUEUE
          value: job1
      restartPolicy: OnFailure
